name: Publish Release
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ./.gradle/loom-caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: preprocessResources
        env:
          BUILD_TYPE: "RELEASE"
        run: ./gradlew preprocessResources
      - name: build
        env:
          BUILD_TYPE: "RELEASE"
        run: ./gradlew build
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: SFO4Ca80
          modrinth-token: ${{ secrets.MODRINTH }}

          curseforge-id: 525510
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: fabricWrapper/build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: fabricWrapper/build/tmp/submods/META-INF/jars/!(*-@(dev|sources|javadoc)).jar

          name: ''
          version-type: release
          changelog: ${{ github.event.release.body }}

          loaders: fabric
          game-versions: |
            1.14.4
            1.15.2
            1.16.5
            1.17.1
            1.18.2
            1.19.2
            1.19.3
            1.19.4
            1.20.1
            1.20.2

          version-resolver: any

          retry-attempts: 3
          retry-delay: 10000